### ISSUE TITLE
Is overtls considering supporting freebsd?

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#74]
There is a serv00 host, but it is a freebsd system. I use the linux package to report an error and request compilation to support freebsd running on serv00.

**Comment by ssrlive** [comment]
please write a CI script reference this sample:
```yaml
name: TestFreeBSD

on:
  [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable"] # ["nightly", "beta", "stable"] #
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            pkg install -y curl pkgconf glib
            curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf > install.sh
            chmod +x install.sh
            ./install.sh -y --default-toolchain ${{ matrix.toolchain }}
          run: |
            . "$HOME/.cargo/env"
            set -ex

            # Add feature "nightly" if toolchain is nightly
            if [ "${{ matrix.toolchain }}" = "nightly" ]; then
                ARGS="$ARGS --features nightly"
            fi

            RUST_BACKTRACE=1 cargo +${{ matrix.toolchain }} fmt --all -- --check
            RUST_BACKTRACE=1 cargo +${{ matrix.toolchain }} clippy --all-features -- -D warnings
            RUST_BACKTRACE=1 cargo +${{ matrix.toolchain }} build --all-features
```
